version: "3.9"
services:
  db:
    image: mysql/mysql-server:${MYSQL_VERSION}
    restart: ${RESTART_EACH_BOOT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"

  adminer:
    depends_on:
      - db
    image: adminer:${ADMINER_VERSION}
    restart: ${RESTART_EACH_BOOT}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8081:8080"