version: '3.9'
services:
  web:
    build: ./web/
    ports:
      - "8501:8501"
    volumes:
      - ./web/app:/app
    depends_on:
      - api

  api:
    build: ./api/
    ports:
      - "8502:80"
    volumes:
      - ./api/app:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=checkpoint-01
    ports:
      - "8503:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
